# Generated by Django 4.1.1 on 2022-09-18 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_rename_comentario_pontoturistico_comentarios'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='comentarios',
        ),
    ]
