# Generated by Django 4.1.1 on 2022-11-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_minima',
            new_name='idade_min',
        ),
    ]
